resolver: lts-11.6

packages:
- .

extra-deps:
  - git: https://github.com/jwaldmann/monadiccp
    commit: a74de358c9a30ddcd86241ee0f915ff57f7ac4ae


system-ghc: true

compiler-check: newer-minor

extra-include-dirs:
  - /opt/gecode/latest/include

extra-lib-dirs:
  - /opt/gecode/latest/lib
